id: IF08A0BCF
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-06-11T13:19:25.776361'
last_modified: '2022-06-11T13:19:25.776366'
parser: null
source_metadata:
  title: Yeshe Tsogyal Series
  language: de
  description: 'Texts related to Yeshe Tsogyal (ye shes mtsho rgyal), the consort
    of Guru Padmasambhava:'
  volume:
    f3377:
      title: A Prayer to Khandro Yeshé Tsogyal
      base_file: f3377.txt
      order: 1
      parent: Prayers
    fFE95:
      title: A Prayer to Lady Yeshe Tsogyal, the Mother
      base_file: fFE95.txt
      order: 2
      parent: Prayers
    f347F:
      title: A Prayer to Yumka Tsogyal
      base_file: f347F.txt
      order: 3
      parent: Prayers
    f5669:
      title: Prayer to Yeshe Tsogyal
      base_file: f5669.txt
      order: 4
      parent: Prayers
    f2FA8:
      title: 'The Tambura’s Yearning Song of Devotion: A Prayer Summarizing Khandro
        Yeshe Tsogyal’s Life and Liberation'
      base_file: f2FA8.txt
      order: 5
      parent: Prayers
    f66A0:
      title: Yeshe Tsogyal's Prayer
      base_file: f66A0.txt
      order: 6
      parent: Prayers
    f6FAC:
      title: 'The Concentrated Essence: A Sādhana of Yeshe Tsogyal'
      base_file: f6FAC.txt
      order: 7
      parent: Sādhanas
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
